### ISSUE TITLE
discord webhook not working since 12/07/2022

### ISSUE THREAD

**Issue by 0-mandrixx-0** [Oonej/RareHunter#8]
discord works fine. their support told me content type --/json was needed now

maybe this is the problem

logs :
================================================ ==========================
07/13/2022 00:02:09
Error: The underlying connection was closed: An unexpected error occurred while sending.
Source: System
Stack: at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at System.Net.WebClient.UploadValues(String address, NameValueCollection data)
   at RareHunter.Discord.Post(String uri, NameValueCollection peers)
   at RareHunter.Discord.threadSend()
Inner: Received an unexpected EOF or 0 bytes from the transport stream.
Inner Stack: at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
================================================ ==========================

**Comment by 0-mandrixx-0** [comment]
discord updated to tls1.2

can be fixed by doing this :

public const SslProtocols _Tls12 = (SslProtocols)0x00000C00;
public const SecurityProtocolType Tls12 = (SecurityProtocolType)_Tls12;

ServicePointManager.SecurityProtocol = Tls12;
